# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

In [2]:
import numpy as np

## Задачи для совместного разбора

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

In [6]:
arr = np.random.uniform(0,20,(4, 7))
arr

array([[ 3.69200333, 14.73999081,  1.21896336, 19.50901422, 17.78943343,
         6.83420778,  6.69429265],
       [ 1.54805888,  7.47119433, 17.67077631,  7.04195581,  4.43799893,
        10.58821196, 15.41349842],
       [17.59609723, 15.16699678,  3.34378688,  5.95580776,  9.01158572,
         5.30108264, 15.85522105],
       [13.22820328,  5.47880482, 19.78757536,  2.22443016,  3.34850287,
         5.12649781, 13.50679066]])

In [9]:
arr_min = np.min(arr)
arr_max = np.max(arr)
(arr-arr_min)/(arr_max-arr_min)

array([[0.13318389, 0.72816576, 0.        , 0.98499828, 0.89239142,
        0.30240518, 0.29487014],
       [0.01772322, 0.33670966, 0.88600122, 0.31359331, 0.17335898,
        0.50457453, 0.76443705],
       [0.88197943, 0.75116188, 0.11443093, 0.25509954, 0.41966639,
        0.21983976, 0.78822573],
       [0.64674947, 0.22941087, 1.        , 0.05414873, 0.11468491,
        0.21043762, 0.6617526 ]])

2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [12]:
arr2 = np.random.uniform(0, 10, (8,10))
arr2

array([[6.13188842, 8.12128946, 6.02399898, 5.80994954, 1.28005992,
        7.88428377, 5.09149632, 7.78140348, 6.8790545 , 2.14174738],
       [6.60889606, 1.91841733, 9.61065336, 8.05481355, 9.23727552,
        5.20864292, 0.03417892, 6.02757693, 7.61970934, 3.78575642],
       [2.12829664, 0.03333082, 1.85331002, 2.83084266, 8.11109263,
        6.92357055, 1.07892658, 8.12381984, 7.97412187, 0.92087137],
       [1.71392681, 5.49627771, 7.18944954, 5.57750556, 4.87660904,
        5.55498291, 3.62466904, 3.06820201, 4.64787859, 6.71752897],
       [3.33505467, 7.18281114, 9.40799828, 4.3149591 , 6.10008176,
        4.3044945 , 9.89542354, 3.07631967, 9.76516621, 0.37595171],
       [5.07522975, 9.69987088, 1.61961453, 1.24187716, 9.68557015,
        5.57508279, 2.97213428, 8.17804997, 6.53661994, 2.37443921],
       [7.58216997, 3.06642535, 2.54484971, 8.00823275, 1.39967621,
        0.6009978 , 6.83307566, 7.10149029, 6.70476393, 4.63025306],
       [4.17103433, 3.07717638, 5.4497451

In [16]:
arr2_argmin = np.argmin(np.sum(arr2, axis=1))
arr2[arr2_argmin]

array([2.12829664, 0.03333082, 1.85331002, 2.83084266, 8.11109263,
       6.92357055, 1.07892658, 8.12381984, 7.97412187, 0.92087137])

3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

In [20]:
arr3 = np.random.randint(0, 10, size=10)
print(arr3)
arr4 = np.random.randint(0, 10, size=10)
print(arr4)
np.linalg.norm(arr3 - arr4)

[8 2 3 0 5 0 0 4 8 2]
[5 3 7 9 2 5 2 9 8 3]


13.076696830622021

4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

In [21]:
a = np.matrix([[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]])
b = np.matrix([[3, -1], [2, 1]])
c = np.matrix([[7, 21], [11, 8], [8, 4]])
np.linalg.inv(a) @ -c @ np.linalg.inv(b)

matrix([[ 1.00000000e+00,  1.11022302e-15],
        [-2.00000000e+00,  1.00000000e+00],
        [ 3.00000000e+00, -4.00000000e+00]])

## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [25]:
my_data = np.loadtxt(r'minutes_n_ingredients.csv', delimiter = ',', dtype=np.int32, skiprows=1)
my_data[:5]

array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       [ 67660,      5,      6],
       [157911,     60,     14]])

2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [26]:
my_data[:,1:].mean(axis=0)

array([2.16010017e+04, 9.05528000e+00])

In [27]:
my_data[:,1:].min(axis=0)

array([0, 1])

In [28]:
my_data[:,1:].max(axis=0)

array([2147483647,         39])

In [29]:
np.median(my_data[:,1:],axis=0)

array([40.,  9.])

3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [34]:
q2 = np.quantile(my_data[:,1], q=0.75, axis=0)
my_data[my_data[:,1]<=q2]

array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       ...,
       [ 43407,     35,      7],
       [498432,     65,     15],
       [370915,      5,      4]])

4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [37]:
mask = my_data[:,1]==0
print(my_data[mask].shape[0])
new_data = my_data.copy()
new_data[mask, 1] = 1
new_data[mask]

479


array([[9325,    1,   10],
       [2828,    1,    8],
       [8008,    1,   11],
       ...,
       [3383,    1,    7],
       [2778,    1,   11],
       [4747,    1,    9]])

5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [45]:
np.unique(my_data, axis=1).shape[0]

100000

6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [48]:
np.unique(my_data[:,2]).shape[0]

37

7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [49]:
my_data[my_data[:,2] <= 5]

array([[446597,     15,      5],
       [204134,      5,      3],
       [ 25623,      6,      4],
       ...,
       [ 52088,     60,      5],
       [128811,     15,      4],
       [370915,      5,      4]])

8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [51]:
new_data[:,2]/new_data[:,1]

array([0.26666667, 0.28      , 0.6       , ..., 0.23076923, 0.8       ,
       0.1       ])

In [52]:
np.max(new_data[:,2]/new_data[:,1])

24.0

9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [64]:
np.sum(my_data[my_data[:, 1].argsort()][::-1][:100,2])/100

6.61

10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [67]:
my_data[np.random.randint(my_data.shape[0], size=10)]

array([[245988,      5,      5],
       [ 82357,     90,      5],
       [128908,     55,     15],
       [206695,     15,      4],
       [299902,      7,     10],
       [123609,     45,      8],
       [362899,     51,     11],
       [ 26946,     20,      5],
       [265524,     15,     13],
       [249511,     60,     13]])

11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [77]:
my_data[my_data[:,2] < my_data[:,2].mean()].shape[0]/my_data.shape[0]*100

58.802

12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [83]:
new_data2 = np.c_[my_data, (my_data[:,1] <= 20) * (my_data[:,2]<=5)]
new_data2

array([[127244,     60,     16,      0],
       [ 23891,     25,      7,      0],
       [ 94746,     10,      6,      0],
       ...,
       [498432,     65,     15,      0],
       [370915,      5,      4,      1],
       [ 81993,    140,     14,      0]])

13. Выведите процент "простых" рецептов в датасете

In [92]:
new_data2[new_data2[:,3]!=0].shape[0]/new_data2.shape[0]*100

9.552

14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [91]:
short_arr = my_data[my_data[:, 2] < 10]
norm_arr = my_data[(my_data[:, 2] >= 10) * (my_data[:,2] < 20)]
long_arr = my_data[my_data[:, 2] >= 20]
max_len = min(short_arr.shape[0], norm_arr.shape[0], long_arr.shape[0])


In [97]:
new_data3 = np.array([short_arr[:max_len], norm_arr[:max_len], long_arr[:max_len]])
new_data3

array([[[ 23891,     25,      7],
        [ 94746,     10,      6],
        [ 67660,      5,      6],
        ...,
        [230210,     30,      6],
        [281614,     25,      8],
        [139843,     50,      6]],

       [[127244,     60,     16],
        [157911,     60,     14],
        [280968,     85,     11],
        ...,
        [382527,     55,     12],
        [ 19716,     30,     10],
        [ 37210,     25,     10]],

       [[504666,     65,     20],
        [ 44512,     50,     20],
        [470973,    180,     20],
        ...,
        [188457,    735,     26],
        [ 51720,     30,     22],
        [451245,    390,     21]]])