# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

## Задачи для совместного разбора

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

## Лабораторная работа №1.1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

In [22]:
import numpy as np
dataset = np.loadtxt("./data/minutes_n_ingredients.csv", delimiter=",", dtype=np.int32, skiprows=1)

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [4]:
# скопируем значения, чтобы не портить исходные данные
restricted_dataset = np.copy(dataset)

In [9]:
# вычислим третий квартиль у минут
q_075 = np.quantile(dataset[:, 1], 0.75)
# ограничение
restricted_dataset[:, 1] = np.clip(restricted_dataset[:, 1], a_min=0, a_max=q_075)
q_075, restricted_dataset[:20]

(65.0,
 array([[127244,     60,     16],
        [ 23891,     25,      7],
        [ 94746,     10,      6],
        [ 67660,      5,      6],
        [157911,     60,     14],
        [152828,     40,      7],
        [ 33941,     18,      9],
        [446597,     15,      5],
        [366174,      7,      9],
        [ 74205,     20,      7],
        [504666,     65,     20],
        [ 81006,     12,      7],
        [280968,     65,     11],
        [204134,      5,      3],
        [ 18593,     35,      7],
        [ 25623,      6,      4],
        [ 65559,     24,     14],
        [ 99836,     65,      7],
        [ 87775,     65,     13],
        [425704,     40,     12]]))

In [2]:
time = file[:, 1]
time_sort = np.sort(time)
limit_length = int(time_sort.size * 0.75)
limit_time = time_sort[:limit_length]
kvant = limit_time[-1]
print("Квантиль:", kvant)
print("Массив времени выполнения рецепта с ограничением:", limit_time)

Квантиль: 65
Массив времени выполнения рецепта с ограничением: [ 0  0  0 ... 65 65 65]


4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [21]:
print(len(np.unique(dataset)))

100545


In [18]:
np.unique(dataset)

array([         0,          1,          2, ...,     537485,     537671,
       2147483647])

5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [11]:
#2 вариант:Но если нет смысла сравнивать столбец с идентификаторами потому что они все уникальны, тогда для сравнения берем 2 и3 столбец:
need_columns=dataset[:,1:3]
unique, counts = np.unique(need_columns, return_counts=True) 
repeats=np.amax(counts)#Максимальное кол-во повторений 
#print(repeats) =26894
# co=result[:,0]
# lenth=np.size(co)
# print("Количество уникальных рецептов (все рецепты - повторы )=", lenth-repeats)

In [17]:
dataset[0,:]

array([127244,     60,     16])

In [14]:
counts[:100]

array([  479,   250,  1738,  3358,  5783, 11997,  9723, 11035, 11327,
       10700, 14469,  8518,  7062,  5392,  3808,  7859,  2036,  1725,
        1222,   694,  6777,   419,   756,   511,   200,  5691,   207,
         477,   335,    88,  7970,   117,   351,   241,    80,  5375,
          75,   185,   176,    49,  6093,    49,   179,    79,    44,
        4957,    55,    74,   102,    19,  4265,    30,    60,    65,
          18,  3039,    22,    65,    31,    12,  4464,    25,    41,
          39,    24,  2355,    16,    35,    32,     4,  2648,     7,
          51,    12,    15,  2711,    11,     7,    19,    11,  1886,
          11,    14,    10,    14,   760,     6,    14,    11,     9,
        1746,     5,     6,     7,     6,   523,    11,    11,     8,
           9], dtype=int64)

In [15]:
len(unique)

656

In [16]:
unique

array([         0,          1,          2,          3,          4,
                5,          6,          7,          8,          9,
               10,         11,         12,         13,         14,
               15,         16,         17,         18,         19,
               20,         21,         22,         23,         24,
               25,         26,         27,         28,         29,
               30,         31,         32,         33,         34,
               35,         36,         37,         38,         39,
               40,         41,         42,         43,         44,
               45,         46,         47,         48,         49,
               50,         51,         52,         53,         54,
               55,         56,         57,         58,         59,
               60,         61,         62,         63,         64,
               65,         66,         67,         68,         69,
               70,         71,         72,         73,        

6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

## Лабораторная работа №1.2

7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [ ]:
arr3 = arr.copy()
arr3 = np.c_[arr3, np.zeros(np.shape(arr)[0])]
arr3 = arr3.astype(float, copy=False)
arr3[:,3] += np.divide(arr3[:, 2], arr3[:, 1], out=arr3[:, 2], where=arr3[:, 1] != 0)
print(arr3)

9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

10. Выберите случайным образом и выведите информацию о 10 различных рецептах

11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [23]:
arr = dataset

In [ ]:
msr = sr2[sr2<sr1]
print(msr.size/sr2.size*100)

In [26]:
length = len(dataset)
mean_int_count = np.sum(dataset[:,2]) / length  # Среднее значение количеств ингредиентов
res_arr = dataset[dataset[:,2] < mean_int_count]  # Массив с элементами < среднего значения
rows, columns = res_arr.shape                   
result = int(rows/length * 100) # Результат в процентах
print(result,'%')

58 %


In [36]:
print(f'{100 * (dataset[:,2] < dataset[:,2].mean()).sum()/dataset.shape[0]:2.2f}%')

58.80%


12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

13. Выведите процент "простых" рецептов в датасете

14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [23]:
arr = dataset

In [24]:
#первый элемент на оси ноль - группа 0
#второй элемент на оси ноль - группа 1 
#третий элемент на оси ноль - группа 2
arr_axis_0_gp_1 = arr[arr[:, 1] < 10]
print(arr_axis_0_gp_1.shape)
arr_axis_0_gp_2 = arr[(arr[:, 1] >= 10) & (arr[:, 1] < 20)]
print(arr_axis_0_gp_2.shape)
arr_axis_0_gp_3 = arr[arr[:, 1] > 20]
print(arr_axis_0_gp_3.shape)

(7588, 3)
(12661, 3)
(73350, 3)


In [25]:
ax1_ln = min(arr_axis_0_gp_1.shape[0], arr_axis_0_gp_1.shape[0], arr_axis_0_gp_2.shape[0])
print('ax1_ln:', ax1_ln)
arr_3D = np.stack((arr_axis_0_gp_1[:ax1_ln], arr_axis_0_gp_2[:ax1_ln], arr_axis_0_gp_3[:ax1_ln]))
print(arr_3D.shape)
print()
print(arr_3D)

ax1_ln: 7588
(3, 7588, 3)

[[[ 67660      5      6]
  [366174      7      9]
  [204134      5      3]
  ...
  [420725      5      3]
  [  4747      0      9]
  [370915      5      4]]

 [[ 94746     10      6]
  [ 33941     18      9]
  [446597     15      5]
  ...
  [  9831     15      7]
  [335859     12     14]
  [256812     10      3]]

 [[127244     60     16]
  [ 23891     25      7]
  [157911     60     14]
  ...
  [ 24549     70      6]
  [449468     50     11]
  [ 28830     65     13]]]
