# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

## Задачи для совместного разбора

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

## Лабораторная работа №1.1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [11]:
import numpy as np
dataset = np.loadtxt("./data/minutes_n_ingredients.csv", delimiter=",", dtype=np.int32, skiprows=1)

2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [7]:
dataset_4 = np.copy(dataset)

In [8]:
ds_time_z = dataset_4[:, 1]==0
len(ds_time_z), ds_time_z[:100]

(100000,
 array([False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False]))

In [9]:
zero_count = np.sum(dataset_4[:, 1]==0)
dataset_4[dataset_4[:, 1]==0]=1
# print(c)
dataset_4[:100]

array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       [ 67660,      5,      6],
       [157911,     60,     14],
       [152828,     40,      7],
       [ 33941,     18,      9],
       [446597,     15,      5],
       [366174,      7,      9],
       [ 74205,     20,      7],
       [504666,     65,     20],
       [ 81006,     12,      7],
       [280968,     85,     11],
       [204134,      5,      3],
       [ 18593,     35,      7],
       [ 25623,      6,      4],
       [ 65559,     24,     14],
       [ 99836,    180,      7],
       [ 87775,     80,     13],
       [425704,     40,     12],
       [101799,     10,      8],
       [106325,     70,     11],
       [ 99283,    315,      6],
       [179504,    150,     11],
       [276123,     60,      7],
       [498382,     85,     18],
       [197140,     40,      6],
       [484223,     18,      4],
       [385472,     90,      9],
       [ 63150,    250,      4],
       [37

5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [10]:
print("Уникальных значений в датасете: ", len(np.unique(dataset[:, 1:])))

Уникальных значений в датасете:  656


6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

## Лабораторная работа №1.2

7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [33]:
dataset_2 = dataset.copy()
with np.errstate(divide="ignore"):
    ingredients_per_minute = np.where(dataset_2[:, 1] != 0, np.around(dataset_2[:, 2] / dataset_2[:, 1], 3), dataset_2[:, 2])
ingredients_per_minute.shape, ingredients_per_minute

((100000,), array([0.267, 0.28 , 0.6  , ..., 0.231, 0.8  , 0.1  ]))

In [34]:
dataset_2 = np.stack((dataset_2[:, 0], ingredients_per_minute), axis=1)
dataset_2.shape, dataset_2

((100000, 2),
 array([[1.27244e+05, 2.67000e-01],
        [2.38910e+04, 2.80000e-01],
        [9.47460e+04, 6.00000e-01],
        ...,
        [4.98432e+05, 2.31000e-01],
        [3.70915e+05, 8.00000e-01],
        [8.19930e+04, 1.00000e-01]]))

In [42]:
a1 = np.arange(1, 10)
print(a1, a1.shape)
a2 = np.arange(1,19).reshape(2, 9)
print(a2, a2.shape)
print(a1[np.newaxis, :])
np.stack((a1[np.newaxis, :], a2), axis=1)

[1 2 3 4 5 6 7 8 9] (9,)
[[ 1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18]] (2, 9)
[[1 2 3 4 5 6 7 8 9]]


ValueError: all input arrays must have the same shape

In [39]:
a1[np.newaxis, :]

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [44]:
dataset_2 = dataset.copy()
with np.errstate(divide="ignore"):
    ingredients_per_minute = np.where(dataset_2[:, 1] != 0, np.around(dataset_2[:, 2] / dataset_2[:, 1], 3), dataset_2[:, 2])
dataset_2 = np.stack((dataset_2[:, 0], ingredients_per_minute), axis=1)
max_ingredients_per_minute = max(ingredients_per_minute)
print(f'Максимальное значение ингредиенты/минуты равняется {max_ingredients_per_minute}')
print(dataset_2)

Максимальное значение ингредиенты/минуты равняется 24.0
[[1.27244e+05 2.67000e-01]
 [2.38910e+04 2.80000e-01]
 [9.47460e+04 6.00000e-01]
 ...
 [4.98432e+05 2.31000e-01]
 [3.70915e+05 8.00000e-01]
 [8.19930e+04 1.00000e-01]]


In [43]:
ingredients_per_minute.max()

24.0

9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

10. Выберите случайным образом и выведите информацию о 10 различных рецептах

11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

13. Выведите процент "простых" рецептов в датасете

14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [13]:
r = dataset.copy()

In [16]:
m1 = r[:,1]<=10
m1

array([False, False,  True, ..., False,  True, False])

In [18]:
m2 = r[:,1]<20
m2

array([False, False,  True, ..., False,  True, False])

In [20]:
m1 * m2

array([False, False,  True, ..., False,  True, False])

In [27]:
short = r[r[:,1]<=10]
standard = r[(r[:,1]>10) & (r[:,1]<20)]
long_last = r[r[:,1]>=20]
l = min(len(short),len(standard),len(long_last))
print(l)

7783


In [30]:
groupped = np.array([short[:l], standard[:l], long_last[:l]])
print(groupped.shape)

(3, 7783, 3)


In [ ]:
short = r.copy()[r.copy()[:,1]<=10]
standard = r.copy()
standard = standard[np.logical_and(standard[:,1]>10, standard[:,1]<20)]
long_last = r.copy()[r.copy()[:,1]>=20]
l = min(len(short),len(standard),len(long_last))
short = short[:l]
standard = standard[:l]
long_last = long_last[:l]
groupped = np.array([short, standard, long_last])
print(np.shape(groupped))